export const ITEMS_LIST_REQUEST = "ITEMS_LIST_REQUEST";
export const ITEMS_LIST_SUCCESS = "ITEMS_LIST_SUCCESS";
export const ITEMS_LIST_FAIL = "ITEMS_LIST_FAIL";

export const ITEMS_CREATE_REQUEST = "ITEMS_CREATE_REQUEST";
export const ITEMS_CREATE_SUCCESS = "ITEMS_CREATE_SUCCESS";
export const ITEMS_CREATE_FAIL = "ITEMS_CREATE_FAIL";
